spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/yilin-reactive?serverZoneId=Asia/Shanghai
    username: root
    password: jcohy1203
  flyway:
    url: jdbc:mysql://localhost:3306/yilin-reactive?serverZoneId=Asia/Shanghai
    locations: "classpath:db/mysql/migration"